// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwjUPqz0Y21LQQBux9nxU7iLpPmrcvbEI',
    appId: '1:381706002013:web:d1b61c16d4c199bfc8f7b4',
    messagingSenderId: '381706002013',
    projectId: 'cars-app-75bcf',
    authDomain: 'cars-app-75bcf.firebaseapp.com',
    storageBucket: 'cars-app-75bcf.firebasestorage.app',
    measurementId: 'G-NKYZEPDMJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5nmD6AfSM8F4xoGia7u5lQpb8pusUc4c',
    appId: '1:381706002013:android:bc682efe31b49827c8f7b4',
    messagingSenderId: '381706002013',
    projectId: 'cars-app-75bcf',
    storageBucket: 'cars-app-75bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr9KDzKWq_3rmGZMEXoLeAdF9GAIcoFYQ',
    appId: '1:381706002013:ios:5defb369a427a4e1c8f7b4',
    messagingSenderId: '381706002013',
    projectId: 'cars-app-75bcf',
    storageBucket: 'cars-app-75bcf.firebasestorage.app',
    iosBundleId: 'com.example.carsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr9KDzKWq_3rmGZMEXoLeAdF9GAIcoFYQ',
    appId: '1:381706002013:ios:5defb369a427a4e1c8f7b4',
    messagingSenderId: '381706002013',
    projectId: 'cars-app-75bcf',
    storageBucket: 'cars-app-75bcf.firebasestorage.app',
    iosBundleId: 'com.example.carsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwjUPqz0Y21LQQBux9nxU7iLpPmrcvbEI',
    appId: '1:381706002013:web:8b4ae95f9f0d3393c8f7b4',
    messagingSenderId: '381706002013',
    projectId: 'cars-app-75bcf',
    authDomain: 'cars-app-75bcf.firebaseapp.com',
    storageBucket: 'cars-app-75bcf.firebasestorage.app',
    measurementId: 'G-GJMMK12QWX',
  );
}
